// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG_J48EFZuA2_BK00I5GxpXkOsQ7fGOZg',
    appId: '1:619501315798:web:3e0480627e4e41b7564b77',
    messagingSenderId: '619501315798',
    projectId: 'speech-aid-5a5f6',
    authDomain: 'speech-aid-5a5f6.firebaseapp.com',
    storageBucket: 'speech-aid-5a5f6.appspot.com',
    measurementId: 'G-917PLNYWQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8aMJbtGNRpsTBt-FsJ1K-VhQKaaNMups',
    appId: '1:619501315798:android:515c9c8bcd1e2de9564b77',
    messagingSenderId: '619501315798',
    projectId: 'speech-aid-5a5f6',
    storageBucket: 'speech-aid-5a5f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ERtD2aYlGHiJwNyC09Pzf61MRGl5jLA',
    appId: '1:619501315798:ios:69a948e174f081ef564b77',
    messagingSenderId: '619501315798',
    projectId: 'speech-aid-5a5f6',
    storageBucket: 'speech-aid-5a5f6.appspot.com',
    iosBundleId: 'com.example.speechAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ERtD2aYlGHiJwNyC09Pzf61MRGl5jLA',
    appId: '1:619501315798:ios:f0eb3eb57d447b94564b77',
    messagingSenderId: '619501315798',
    projectId: 'speech-aid-5a5f6',
    storageBucket: 'speech-aid-5a5f6.appspot.com',
    iosBundleId: 'com.example.speechAid.RunnerTests',
  );
}
